import React from 'react';
import CodeBlock from '@theme/CodeBlock';
import clsx from 'clsx';
import styles from './styles.module.css';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'; // Import the FontAwesomeIcon component.

const code = `\
# Retrieve the list of users that:
# - have their Date Of Birth(dob) later than Jan 1st, 2000
# - paginated in groups of 50 by email order(from start)
# - sort results by ascending email, then descending dob
# - return only their id, email, dob and friend collection
# - with each friend only returning their name and phone

$ curl 'http://localhost:9292/api/users' - G \\
--data - urlencode "filters=dob>2000-01-01" \\
--data - urlencode "pagination=by=email,items=50" \\
--data - urlencode "order=email,-dob" \\
--data - urlencode "fields=id,email,dob,friends{name,phone}" \\
[
  {
    "id": 33,
    "email": "koolcat@example.com",
    "dob": "2005-05-05",
    "fiends": [
      { "name": "Mr. Mouse", phone: "555-1234" },
      { "name": "Duck", phone: "555-2222" },
    ]
  },
  {
    "id": 1,
    "email": "loosemoose@example.co,",
    "dob": "2009-01-15",
    "fiends": [
      { "name": "Chicken", phone: "555-9999" }
    ]
  },
...
`;
export default function HomepageSection() {
  return (
    <>
      <section className={styles.features} >
        <div className="row" style={{ width: '85%', alignItems: 'center' }}>
          <div className={clsx('col col--6')}>
            <CodeBlock language='ruby'>
              {code}
            </CodeBlock>
            <div className="summary" style={{ fontStyle: 'italic', fontSize: '16px', marginTop: '15px', marginBottom: '0px' }}>
              The implementation of the example above requires literally no controller code, or manual crafting of DB queries to be written, when several of the add-ons have been enabled.
            </div>
          </div>
          <div className={clsx('col col--6')} style={{ paddingLeft: '40px' }}>
            <h2 className={styles.title}>
              <FontAwesomeIcon icon="fa fa-battery-half" style={{ paddingRight: '10px' }} />
              With batteries included
            </h2>
            <ul className="featureList">
              <li>Automatic enforcement of your API design</li>
              <li>Automatic generation of Open API 3.x docs</li>
              <li>Built-in GraphQL-style field selection</li>
              <li>Integrated pagination and ordering</li>
              <li>Seamless and consistent filtering of results</li>
              <li>Smart, autogenerated and predictable DB queries</li>
              <li>Fast runtime results with Ruby's readibility</li>
              <li>Built atop of Rack, and based on standards</li>
              <li>Fully configurable, include only features you need</li>
              <li>Embeddable with Rails, to reuse your existing code</li>
              <li>Fast and flexible routing, API versioning, etc...</li>
              <li>API design separate from implementation details</li>
              <li>and the list goes on...</li>
            </ul>
          </div>
        </div>
      </section>
    </>
  );
}
